### ISSUE TITLE
Message buffer too big!

### ISSUE THREAD

**Issue by Anatoly03** [RonenNess/EzSockets#1]
```
Error! System.Exception: Message buffer too big!
   at EzSockets.EzSocket.ReadMessageAsync()
```

Running the example code gives this error. From the default code I've made the server a static method and in Main call the thread to sleep at -1, so the console doesn't close:

```cs
static void Main(string[] args)
{
            Console.WriteLine("Hello World!");
            server.ListenAsync(8080);
            Thread.Sleep(-1);
}
```

Also did a slight change to transform the message to string

```
            OnMessageReadHandler = (EzSocket socket, byte[] data) =>
            {
                Console.WriteLine("Read message!");
                socket.SendMessage(EzSocket.BytesToString(data));
            },
            OnMessageSendHandler = (EzSocket socket, byte[] data) =>
            {
                Console.WriteLine("Sent message!");
                Console.WriteLine(EzSocket.BytesToString(data));
            },
```

The client code is not c#, but should be working.

**Comment by RonenNess** [comment]
Change `EzSocket.MaxMessageSize` to something bigger.
Honestly I don't even remember why I added this validation.. I think you can set it to a really large value and it would be OK.

**Comment by playingoDEERUX** [comment]
@RonenNess It still doesn't work after doing this change... When do I set it?
